--//Function
getgenv().Version = 1.0
getgenv().AutoFarm = false;


local table1 = {}
local table2 = {}

for i,v in pairs(game:GetService("Workspace").Enemies:GetChildren()) do 
table.insert(table1, v.Name)
end

for i,v in pairs(game:GetService("Workspace").QuestNPCs:GetChildren()) do 
 table.insert(table2,v.Name)
end

function Tp(name)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "world"
local ohString2 = name

game:GetService("ReplicatedStorage").Remotes.RequestTeleport:InvokeServer(ohString1, ohString2)

end


local library = loadstring(game:HttpGet(('https://raw.githubusercontent.com/bloodball/-back-ups-for-libs/main/wall%20v3')))()

local w = library:CreateWindow("XenijosFunScript") 

local b = w:CreateFolder("Main") 

local y = w:CreateFolder("TP")


local enemies = game:GetService("Workspace").Enemies
local selectedEnemy = nil

local area
local dropdown = b:Dropdown("Farm World",table1,true,function(Area)
area = Area
end)

local running = true
b:Toggle("Auto", function(bool)
    if bool then
        running = true
        while running do 
            if enemies:FindFirstChild(area) then
                local selectedArea = enemies:FindFirstChild(area)
                if selectedArea then
                    for i,v in pairs(selectedArea:GetChildren()) do
                        local humanoidRootPart = v:FindFirstChild("HumanoidRootPart")
                        if humanoidRootPart then
                            if i == 1 then
                                selectedEnemy = humanoidRootPart.Parent
                                print("Selected enemy:", selectedEnemy)
                            end
                            break
                        else
                            print("Humanoid Root Part not found")
                        end
                    end
                else
                    print("Selected folder is empty")
                end
            else
                print("Invalid selection")
            end

            game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = selectedEnemy.HumanoidRootPart.CFrame
            game:GetService("ReplicatedStorage").Remotes.WeaponRemote:FireServer(selectedEnemy)
            wait(0.125)
        end
        print("Enemy has been defeated.")
    else
        running = false
        print("AutoKill toggle is off.")
    end
end)


local map
y:Dropdown("World To Tp",table2,true,function(mob) --true/false, replaces the current title "Dropdown" with the option that t
    print(mob)
    map = mob
end)

y:Button("Tp",function()
    Tp(map)
end)


b:DestroyGui()

