--//Functions
getgenv().version = 1.0

if game.PlaceId == "3102144307" then

local table1 = {}

local table2 = {}

local table3 = {}

for i,v in pairs(game:GetService("Workspace").Eggs:GetChildren()) do 
    table.insert(table1, v.Name)
end

for i,v in pairs(game:GetService("Workspace").PickupSpawns:GetChildren()) do 
    table.insert(table2, v.Name)
end

for i,v in pairs(game:GetService("Workspace").BossZones:GetChildren()) do 
    table.insert(table3, v.Name)
end

local RemotePath = game:GetService("ReplicatedStorage").Remotes;


getgenv().autotap = false;
getgenv().bosskill = false;

function Click()
    spawn(function()
while autotap == true do 



local args = {
    [1] = false,
    [2] = "Clicker!"
}

RemotePath.ClickRemote:FireServer(unpack(args))

wait()
end
end)
end


function Open(Name)
    spawn(function()
        
    -- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = Name
local ohBoolean2 = false
local ohBoolean3 = false

game:GetService("ReplicatedStorage").Remotes.OpenEgg:InvokeServer(ohString1, ohBoolean2, ohBoolean3)
    end)
end


function TP(World)
    spawn(function()
        -- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "world"
local ohString2 = World

game:GetService("ReplicatedStorage").Remotes.RequestTeleport:InvokeServer(ohString1, ohString2)
    end)
end


function BossKIll(p)
  spawn(function()
    while bosskill == true do 
 wait()

local ohBoolean1 = false
local ohBoolean2 = false
local ohString3 = "Clicker!"
local ohString4 = p

game:GetService("ReplicatedStorage").Remotes.ClickRemote:FireServer(ohBoolean1, ohBoolean2, ohString3, ohString4)
    end
end)
end



--//Script
local library = loadstring(game:HttpGet(('https://raw.githubusercontent.com/bloodball/-back-ups-for-libs/main/wall%20v3')))()

local w = library:CreateWindow("XenijosFunScript") -- Creates the window

local b = w:CreateFolder("Main") -- Creates the folder(U will put here your buttons,etc)



b:Toggle("AutoClicker",function(bool)
    getgenv().autotap = bool
    print("Auto Tap is: ", bool);
    if bool then 
     Click();
    end

end)

local name 
b:Dropdown("Eggs",table1,true,function(value) --true/false, replaces the current title "Dropdown" with the option that t
    name = value
end)

b:Button("Open Egg",function()
    Open(name)
end)


local name 
b:Dropdown("World",table2,true,function(value) --true/false, replaces the current title "Dropdown" with the option that t
    names = value
end)

b:Button("TP TO WORLD",function()
    TP(names)
end)


local named 
b:Dropdown("Bosses",table3,true,function(value) --true/false, replaces the current title "Dropdown" with the option that t
    named = value
end)

b:Button("TP TO BOSS",function()
   game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = game:GetService("Workspace").BossZones[named].SpawnCF.CFrame
end)


b:Toggle("Kill Boss",function(bool)
    getgenv().bosskill = bool
    print("Auto Boss Kill is: ", bool);
    if bool then 
     BossKIll(named)
    end
end)


--[[
b:Label("Pretty Useless NGL",{
    TextSize = 25; -- Self Explaining
    TextColor = Color3.fromRGB(255,255,255); -- Self Explaining
    BgColor = Color3.fromRGB(69,69,69); -- Self Explaining
    
}) 

b:Button("Button",function()
    print("Elym Winning")
end)

b:Toggle("Toggle",function(bool)
    shared.toggle = bool
    print(shared.toggle)
end)

b:Slider("Slider",{
    min = 10; -- min value of the slider
    max = 50; -- max value of the slider
    precise = true; -- max 2 decimals
},function(value)
    print(value)
end)

b:Dropdown("Dropdown",{"A","B","C"},true,function(mob) --true/false, replaces the current title "Dropdown" with the option that t
    print(mob)
end)

b:Bind("Bind",Enum.KeyCode.C,function() --Default bind
    print("Yes")
end)

b:ColorPicker("ColorPicker",Color3.fromRGB(255,0,0),function(color) --Default color
    print(color)
end)

b:Box("Box","number",function(value) -- "number" or "string"
    print(value)
end)
]]
b:DestroyGui()
end
